name: Deploy M-Pathy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: m-pathy-deploy
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build Next.js
        env:
          NEXT_TELEMETRY_DISABLED: '1'
        run: npm run build

      # === Snapshot-Packaging, verhindert "file changed as we read it" ===
      - name: Package artifact (stable snapshot)
        run: |
          set -euxo pipefail
          mkdir -p package-src
          rsync -a --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.next/cache' \
            ./ package-src/
          tar -C package-src -czf m-pathy.tar.gz .

      - name: Upload to server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY : ${{ secrets.HETZNER_SSH_KEY }}
        run: |
          set -euxo pipefail
          printf "%s" "$SSH_KEY" > key.pem
          chmod 600 key.pem
          scp -P "${SSH_PORT:-22}" -i key.pem -o StrictHostKeyChecking=no m-pathy.tar.gz "${SSH_USER}@${SSH_HOST}:/tmp/m-pathy.tar.gz"

      - name: Deploy on server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          set -euxo pipefail
          ssh -p "${SSH_PORT:-22}" -i key.pem -o StrictHostKeyChecking=no "${SSH_USER}@${SSH_HOST}" 'bash -s' <<'REMOTE'
            set -euxo pipefail
            sudo mkdir -p /srv/m-pathy
            sudo tar -xzf /tmp/m-pathy.tar.gz -C /srv/m-pathy
            sudo chown -R deploy:deploy /srv/m-pathy
            cd /srv/m-pathy
            npm ci --omit=dev
            sudo systemctl restart m-pathy
REMOTE

      - name: Cleanup key
        if: always()
        run: rm -f key.pem
