name: Deploy M-Pathy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install & Build
        run: |
          set -e
          npm ci
          npm run build

      - name: Package artifact (snapshot safe)
        run: |
          set -e
          SNAP="$(mktemp -d)"
          mkdir -p "$SNAP/package-src"
          rsync -a --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.next/cache' \
            ./ "$SNAP/package-src"/
          tar -C "$SNAP/package-src" -czf m-pathy.tar.gz .
          rm -rf "$SNAP"

      - name: Upload artifact via scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          source: "m-pathy.tar.gz"
          target: "/tmp"

      - name: Write /etc/m-pathy.env on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            set -e
            sudo bash -c 'cat > /etc/m-pathy.env' <<'EOF'
            AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }}
            AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }}
            AZURE_OPENAI_DEPLOYMENT=${{ secrets.AZURE_OPENAI_DEPLOYMENT }}
            AZURE_OPENAI_API_VERSION=${{ secrets.AZURE_OPENAI_API_VERSION }}
            NODE_ENV=production
            PORT=3000
            EOF
            sudo chmod 600 /etc/m-pathy.env

      - name: Remote deploy (atomic switch)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            set -e
            ARCHIVE=/tmp/m-pathy.tar.gz
            NEW=/srv/m-pathy.new
            CUR=/srv/m-pathy

            sudo systemctl stop m-pathy || true
            sudo rm -rf "$NEW"
            sudo mkdir -p "$NEW"
            sudo tar -C "$NEW" -xzf "$ARCHIVE"
            sudo rm -f "$ARCHIVE"

            test -f "$NEW/package.json" || { echo "Missing package.json after extract" >&2; exit 1; }

            sudo rm -rf "${CUR}.prev" || true
            [ -d "$CUR" ] && sudo mv "$CUR" "${CUR}.prev" || true
            sudo mv "$NEW" "$CUR"

            cd "$CUR"
            npm ci --omit=dev

            sudo systemctl daemon-reload || true
            sudo systemctl restart m-pathy
            sudo systemctl status m-pathy --no-pager -l | head -n 60 || true
