name: Deploy M-Pathy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Build (Next.js)
        run: |
          set -e
          npm ci
          npm run build

      - name: Package artifact (stable snapshot)
        run: |
          set -e
          SNAP="$(mktemp -d)"
          mkdir -p "$SNAP/package-src"
          rsync -a --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.next/cache' \
            ./ "$SNAP/package-src"/
          tar -C "$SNAP/package-src" -czf m-pathy.tar.gz .
          rm -rf "$SNAP"

      - name: Upload artifact to server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          HETZNER_SSH_KEY: ${{ secrets.HETZNER_SSH_KEY }}
        run: |
          set -e
          umask 077
          printf "%s\n" "$HETZNER_SSH_KEY" > key.pem
          scp -i key.pem -P "$SSH_PORT" -o StrictHostKeyChecking=accept-new \
            m-pathy.tar.gz "$SSH_USER@$SSH_HOST:/tmp/m-pathy.tar.gz"

      - name: Deploy on server (atomic switch)
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_DEPLOYMENT }}
          AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
        run: |
          set -e
          ssh -i key.pem -p "$SSH_PORT" -o StrictHostKeyChecking=accept-new \
            "$SSH_USER@$SSH_HOST" 'bash -s' <<'REMOTE'
            set -e
            ARCHIVE=/tmp/m-pathy.tar.gz
            APP_NEW=/srv/m-pathy.new
            APP_CUR=/srv/m-pathy
            ENV_FILE=/etc/m-pathy.env

            sudo systemctl stop m-pathy || true
            sudo rm -rf "$APP_NEW"
            sudo mkdir -p "$APP_NEW"
            sudo tar -C "$APP_NEW" -xzf "$ARCHIVE"
            sudo rm -f "$ARCHIVE"

            # Sicherstellen, dass package.json existiert
            test -f "$APP_NEW/package.json" || { echo "Missing package.json after extract" >&2; exit 1; }

            # ENV schreiben (Werte wurden bereits im Runner expandiert)
REMOTE
          # die ENV-Inhalte als Klartext erzeugen und via SSH anhängen
          ssh -i key.pem -p "$SSH_PORT" -o StrictHostKeyChecking=accept-new \
            "$SSH_USER@$SSH_HOST" "sudo tee /etc/m-pathy.env >/dev/null" <<EOF
AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
AZURE_OPENAI_DEPLOYMENT=${AZURE_OPENAI_DEPLOYMENT}
AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
NODE_ENV=production
PORT=3000
EOF
          ssh -i key.pem -p "$SSH_PORT" -o StrictHostKeyChecking=accept-new \
            "$SSH_USER@$SSH_HOST" 'bash -s' <<'REMOTE'
            set -e
            sudo chmod 600 /etc/m-pathy.env

            # Atomare Umschaltung
            APP_NEW=/srv/m-pathy.new
            APP_CUR=/srv/m-pathy
            sudo rm -rf "${APP_CUR}.prev" || true
            [ -d "$APP_CUR" ] && sudo mv "$APP_CUR" "${APP_CUR}.prev" || true
            sudo mv "$APP_NEW" "$APP_CUR"

            # Install & Start
            cd "$APP_CUR"
            npm ci --omit=dev
            sudo systemctl daemon-reload || true
            sudo systemctl start m-pathy
            sudo systemctl status m-pathy --no-pager -l | head -n 60 || true
REMOTE

      - name: Cleanup key
        if: always()
        run: rm -f key.pem
